title: Technical notes of henryhlc
description: >
  henryhlc's notes about algorithms, programming and other topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://henryhlc.github.io"
github_username: henryhlc

# Build settings
# theme: minima
remote_theme: riggraz/no-style-please
theme_config: 
  appearance: "dark"
  date_format: "%Y-%m-%d"
  back_home_text: "<--"
plugins:
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
